version: '3.1'

services:

  springboot:
    image: orioltristany/myspringboot
    build:
      context: .
      dockerfile: Dockerfile-springboot
    depends_on:
      - redis

  redis:
    image: orioltristany/myredis
    build:
      context: .
      dockerfile: Dockerfile-redis
    ports:
      - 6379:6379