apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-standalone
  labels:
    run: redis-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis-standalone
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: redis-standalone
    spec:
      containers:
        - image: orioltristany/myredis
          name: redis-standalone
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: redis-alone
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-standalone-service
  labels:
    run: redis-standalone
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
      name: redis-port
  selector:
    run: redis-standalone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspringboot
  labels:
    run: myspringboot
spec:
  replicas: 1
  selector:
    matchLabels:
      run: myspringboot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: myspringboot
    spec:
      containers:
        - image: orioltristany/myspringboot
          name: myspringboot
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: APPLICATION_REDIS_HOST
              value: redis-standalone-service